name: nyc_airbnb_dev
channels:
  - conda-forge
#  - defaults
dependencies:
  - python=3.10
  - jupyter
  - mlflow
  - hydra-core
  - pandas
  - cookiecutter
  - wandb
#  - matplotlib=3.3.4
#  - git=2.30.2
#  - pip=20.3.3
#  - pip:
#      - wandb==0.10.31
