name: nyc_airbnb_dev
channels:
  - conda-forge
#  - defaults
dependencies:
  - python=3.10
  - jupyter=1.0.0
  - mlflow=1.25.1
  - hydra-core=1.1.1
  - pandas=1.4.2
  - cookiecutter=1.7.3
  - wandb=0.12.14
  - black
  - pyarrow=7.0.0
#  - matplotlib=3.3.4
#  - git=2.30.2
#  - pip=20.3.3
#  - pip:
#      - wandb==0.10.31
